### ISSUE TITLE
*nix_Etc_Path文件名问题

### ISSUE THREAD

**Issue by corp0ra1** [gh0stkey/Web-Fuzzing-Box#1]
hello，师傅，麻烦重新命令下这个文件夹的名字
因为windows下会报错“fatal: cannot create directory at 'Web/*nix_Etc_Path': Invalid argument”
根本原因在于“*”这个特殊字符在windows下不被允许

**Comment by gh0stkey** [comment]
感谢，由于个人一直是在Mac上使用，没考虑环境问题，已经重命名了。
