### ISSUE TITLE
请问一下，文件上传的字典里，识别不了的字符应该怎么进行fuzz。

### ISSUE THREAD

**Issue by littleheary** [gh0stkey/Web-Fuzzing-Box#2]
那个All_Upload_Fuzz.txt这个文件里，有很多十六进制不同，但是ascii解析都是乱码的，即使是传到burp里，也是乱码。像这种，应该怎么fuzz呀？
请大佬指点一下。

**Comment by gh0stkey** [comment]
可以url编码一下试试。
